# Generated by Django 5.1.4 on 2024-12-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('temperatura_dht', models.FloatField()),
                ('umidade', models.FloatField()),
                ('temperatura_bmp', models.FloatField()),
                ('pressao_bmp', models.FloatField()),
                ('anemometro', models.FloatField()),
                ('biruta', models.TextField()),
                ('pluviometro', models.FloatField()),
            ],
        ),
    ]
